[package]
name = "these-macros-should-be-illegal"
version = "0.3.2"
edition.workspace = true
description = "A personal collection of experimental Rust procedural macros"
license = "MIT"
homepage = "https://github.com/AlexanderGolys/these-macros-should-be-illegal"
repository = "https://github.com/AlexanderGolys/these-macros-should-be-illegal"
documentation = "https://docs.rs/these-macros-should-be-illegal"
readme = "README.md"
keywords = ["procedural-macro", "syntax", "experimental"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = { version = "2.0", features = ["full", "parsing", "visit-mut"] }

[dev-dependencies]
prettyplease = "0.2"
serde = { version = "1.0", features = ["derive"] }

[lints.rust]
missing_docs = "deny"

[lints.clippy]
missing_docs_in_private_items = "deny"

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
