#![no_main]
use these_macros_should_be_illegal::enum_fn;
pub enum Action {
    Quit,
    Submit,
    InsertNewline,
}
#[automatically_derived]
impl ::core::clone::Clone for Action {
    #[inline]
    fn clone(&self) -> Action {
        *self
    }
}
#[automatically_derived]
impl ::core::marker::Copy for Action {}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for Action {}
#[automatically_derived]
impl ::core::cmp::PartialEq for Action {
    #[inline]
    fn eq(&self, other: &Action) -> bool {
        let __self_discr = ::core::intrinsics::discriminant_value(self);
        let __arg1_discr = ::core::intrinsics::discriminant_value(other);
        __self_discr == __arg1_discr
    }
}
#[automatically_derived]
impl ::core::cmp::Eq for Action {
    #[inline]
    #[doc(hidden)]
    #[coverage(off)]
    fn assert_receiver_is_total_eq(&self) -> () {}
}
impl Action {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub const fn description(&self) -> &'static str {
        match self {
            Self::Quit => "quit spectral-m2",
            Self::Submit => "evaluate the input",
            Self::InsertNewline => "insert a line break",
        }
    }
}
pub enum Message {
    Tuple(u16),
    Struct { code: u8 },
    Dynamic(String),
}
impl Message {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub fn description(&self) -> &str {
        match self {
            Self::Tuple(..) => "tuple payload",
            Self::Struct { .. } => "struct payload",
            Self::Dynamic { 0: value, .. } => value,
        }
    }
}
pub enum Selected<'a> {
    Tuple(String, String),
    Struct { a: String, b: String },
    Borrowed(&'a str),
}
impl<'a> Selected<'a> {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub fn description(&self) -> &str {
        match self {
            Self::Tuple { 1: value, .. } => value,
            Self::Struct { a: value, .. } => value,
            Self::Borrowed { 0: value, .. } => value,
        }
    }
}
pub enum Computed<'a> {
    Tuple(&'a str, &'a str),
    Named { code: u8, text: &'a str },
    Unit,
}
impl<'a> Computed<'a> {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub fn description(&self) -> &str {
        match self {
            Self::Tuple(__enum_fn_field_0, __enum_fn_field_1) => {
                (|_: &&'a str, text: &&'a str| {
                    *text
                })(__enum_fn_field_0, __enum_fn_field_1)
            }
            Self::Named {
                code: __enum_fn_field_0,
                text: __enum_fn_field_1,
            } => {
                (|_: &u8, text: &&'a str| *text)(__enum_fn_field_0, __enum_fn_field_1)
            }
            Self::Unit => (|| "unit")(),
        }
    }
}
pub enum ConstComputed<'a> {
    Tuple(&'a str, &'a str),
    Unit,
}
impl<'a> ConstComputed<'a> {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub const fn description(&self) -> &str {
        match self {
            Self::Tuple(__enum_fn_field_0, __enum_fn_field_1) => {
                let (__enum_fn_argument_0, __enum_fn_argument_1) = (
                    __enum_fn_field_0,
                    __enum_fn_field_1,
                );
                let _ = __enum_fn_argument_0;
                let text = __enum_fn_argument_1;
                *text
            }
            Self::Unit => {
                let () = ();
                "unit"
            }
        }
    }
}
pub enum Optional<'a> {
    Fixed,
    Borrowed(&'a str),
    Missing,
    Payload(u8),
}
impl<'a> Optional<'a> {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub fn description(&self) -> ::core::option::Option<&str> {
        match self {
            Self::Fixed => ::core::option::Option::Some("fixed"),
            Self::Borrowed { 0: value, .. } => ::core::option::Option::Some(value),
            Self::Missing => ::core::option::Option::None,
            Self::Payload(..) => ::core::option::Option::None,
        }
    }
}
pub enum OptionalFixed {
    Fixed,
    Missing,
}
impl OptionalFixed {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub const fn description(&self) -> ::core::option::Option<&'static str> {
        match self {
            Self::Fixed => ::core::option::Option::Some("fixed"),
            Self::Missing => ::core::option::Option::None,
        }
    }
}
pub enum Stringified {
    Fixed,
    Missing,
    Payload(u8),
}
impl Stringified {
    ///Returns this variant's `description` value generated by `enum_fn`.
    pub const fn description(&self) -> &'static str {
        match self {
            Self::Fixed => "fixed override",
            Self::Missing => "Missing",
            Self::Payload(..) => "Payload",
        }
    }
}
