#![no_main]

use these_macros_should_be_illegal::str_disc;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Quit,
    Submit,
    InsertNewline,
}

impl Action {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub const fn description(&self) -> &'static str {
        match self {
            Self::Quit => "quit spectral-m2",
            Self::Submit => "evaluate the input",
            Self::InsertNewline => "insert a line break",
        }
    }
}

pub enum Message {
    Tuple(u16),
    Struct { code: u8 },
    Dynamic(String),
}

impl Message {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub fn description(&self) -> &str {
        match self {
            Self::Tuple(..) => "tuple payload",
            Self::Struct { .. } => "struct payload",
            Self::Dynamic(value) => value.as_str(),
        }
    }
}

pub enum Selected<'a> {
    Tuple(String, String),
    Struct { a: String, b: String },
    Borrowed(&'a str),
}

impl<'a> Selected<'a> {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub fn description(&self) -> &str {
        match self {
            Self::Tuple(_, value) => value.as_str(),
            Self::Struct { a: value, .. } => value.as_str(),
            Self::Borrowed(value) => *value,
        }
    }
}

pub enum Optional<'a> {
    Fixed,
    Borrowed(&'a str),
    Missing,
    Payload(u8),
}

impl<'a> Optional<'a> {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub fn description(&self) -> ::core::option::Option<&str> {
        match self {
            Self::Fixed => ::core::option::Option::Some("fixed"),
            Self::Borrowed(value) => ::core::option::Option::Some(*value),
            Self::Missing => ::core::option::Option::None,
            Self::Payload(..) => ::core::option::Option::None,
        }
    }
}

pub enum OptionalFixed {
    Fixed,
    Missing,
}

impl OptionalFixed {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub const fn description(&self) -> ::core::option::Option<&'static str> {
        match self {
            Self::Fixed => ::core::option::Option::Some("fixed"),
            Self::Missing => ::core::option::Option::None,
        }
    }
}

pub enum Stringified {
    Fixed,
    Missing,
    Payload(u8),
}

impl Stringified {
    #[doc = "Returns this variant's `description` value generated by `str_disc`."]
    pub const fn description(&self) -> &'static str {
        match self {
            Self::Fixed => "fixed override",
            Self::Missing => "Missing",
            Self::Payload(..) => "Payload",
        }
    }
}
