//! Local bindings called with function-like syntax through their `callable` alias.

use proc_macro2::{Span, TokenStream};
use quote::quote;
use syn::{
    Error, Expr, Ident, Token,
    ext::IdentExt,
    parse::{Parse, ParseStream},
    parse2,
};

use crate::attr::callable::CALL_METHOD;

/// One local binding and the macro that invokes it.
struct FunctionBinding {
    /// Whether the generated binding may be mutably borrowed by its call method.
    mutability: Option<Token![mut]>,
    /// Shared name of the value and macro.
    name: Ident,
    /// Expression stored in the local binding.
    value: Expr,
}

impl Parse for FunctionBinding {
    /// Parses `[mut] name = expression`.
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mutability = input.parse()?;
        let name = Ident::parse_any(input)?;
        input.parse::<Token![=]>()?;
        let value = input.parse()?;
        input.parse::<Option<Token![;]>>()?;
        Ok(Self {
            mutability,
            name,
            value,
        })
    }
}

macro_docs! {
    /// Creates a local value and a same-name macro providing function-like calls.
    ///
    /// The value's type must expose the method generated by [`callable`]. The
    /// accepted syntax is `[mut] name = expression`.
    ///
    /// # Examples
    ///
    /// ```
    /// use these_macros_should_be_illegal::{callable, make_fn};
    ///
    /// #[callable(apply)]
    /// trait Action {
    ///     fn apply(&self, point: usize) -> usize;
    /// }
    ///
    /// struct Shift(usize);
    ///
    /// impl Action for Shift {
    ///     fn apply(&self, point: usize) -> usize {
    ///         point + self.0
    ///     }
    /// }
    ///
    /// make_fn!(sigma = Shift(3));
    /// assert_eq!(sigma!(2), 5);
    /// ```
}

/// Creates a local value and a same-name macro forwarding to its call alias.
pub fn make_fn(input: TokenStream) -> TokenStream {
    parse2::<FunctionBinding>(input)
        .map(expand_function_binding)
        .unwrap_or_else(Error::into_compile_error)
}

/// Emits the local binding followed by its function-like forwarding macro.
fn expand_function_binding(binding: FunctionBinding) -> TokenStream {
    let FunctionBinding {
        mutability,
        name,
        value,
    } = binding;
    let call_name = Ident::new(CALL_METHOD, Span::call_site());

    quote! {
        let #mutability #name = #value;
        macro_rules! #name {
            ($($arguments:tt)*) => {
                #name.#call_name($($arguments)*)
            };
        }
    }
}

/// Binding and forwarding-macro generation.
#[cfg(test)]
mod tests {
    use quote::quote;

    use super::make_fn;

    /// The binding macro emits exactly one deferred argument repetition.
    #[test]
    fn creates_a_same_name_macro() {
        let output = make_fn(quote!(mut sigma = build())).to_string();

        assert!(output.contains("let mut sigma = build ()"));
        assert!(output.contains("macro_rules ! sigma"));
        assert!(output.contains("sigma . __priv_tmsbi_call"));
    }
}
